site_name: "2100"
site_url: https://lucasvance.github.io/2100/
site_description: "2100"

theme:
    name: material
    palette:
        scheme: slate
    features:
        - toc.integrate # Puts the Table of Contents on the left, keeping the reading flow clean
        - content.footnote.tooltips
        - content.tooltips

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - footnotes
    - abbr

nav:
    - Home: index.md
    - "Part 1: State vs. Corporation": state-vs-corp.md
    - "Part 2: Capitalism is not a free market": liberty.md
    - "Part 3: The freed market": freed-market.md
    - More:
          - Objections and resources: more/objections-resources.md
          - My guess at a future: more/guess.md
          - Intellectual history: more/history.md
          - Bailout history: more/bailouts.md
          - The Constitution was a coup: more/coup.md
          - My guess at a future: more/guess.md
